### ISSUE TITLE
problem about infertence

### ISSUE THREAD

**Issue by SakuBorder** [YihongSun/Dynamo-Depth#1]
Nice work! I wonder whether this can be directly applied to my own dataset for depth/disparity estimation, or if it's possible to train on my own dataset?

**Comment by YihongSun** [comment]
Hello,

Depending on how similar the inference data distribution is to the training distribution (either KITTI, nuScenes, or Waymo), you might expect different levels of performance on the inference images.

Alternatively, you can certainly train on your custom dataset by adding a `custom_dataset.py` in [datasets/](https://github.com/YihongSun/Dynamo-Depth/tree/main/datasets/).

**Comment by SakuBorder** [comment]
> Hello,
> 
> Depending on how similar the inference data distribution is to the training distribution (either KITTI, nuScenes, or Waymo), you might expect different levels of performance on the inference images.
> 
> Alternatively, you can certainly train on your custom dataset by adding a `custom_dataset.py` in [datasets/](https://github.com/YihongSun/Dynamo-Depth/tree/main/datasets/).

thinks,i will have a try
