### ISSUE TITLE
Google form for Waymo checkpoint is not available

### ISSUE THREAD

**Issue by min-hieu-netropy** [YihongSun/Dynamo-Depth#13]
Hi, I can't access the waymo checkpoint form request and wonder if you guys could make it public?

**Comment by YihongSun** [comment]
Hi,

Thank you for your interest in our work!

I am not able to replicate this error as the [form](https://forms.gle/nRezg2gr7QDXJGcA9) is available on my side, with and without incognito. Perhaps try again or attach the error message?

Hope this helps!

**Comment by min-hieu-netropy** [comment]
Hi, 

I got the following message when accessing the link
![image](https://github.com/user-attachments/assets/d08475c5-0fb1-4d9c-b086-1f8c162da58b)

Cheers.

**Comment by YihongSun** [comment]
This appears to be an issue with the account that you're logged in with. 

Can you try with another/personal account instead?

**Comment by min-hieu-netropy** [comment]
Oh it seemed like it was the account that I was on. Thank you for the prompt response!
