### ISSUE TITLE
Does Dynamo-Depth assume access to GT intrinsics during training and inference?

### ISSUE THREAD

**Issue by andrewsonga** [YihongSun/Dynamo-Depth#2]
Hello Yihong,

Thank you for releasing the code for your project. It was an interesting read.

In the paper, it saids, "On all datasets, we only use the unlabeled video frames for training."
I was just wondering if Dynamo-Depth also assumes access to GT camera intrinsics during training and inference?
There does not seem to be separate mechanism for predicting the camera intrinsics.

Thank you in advance!

**Comment by YihongSun** [comment]
Hi Andrew,

Your intuition is correct. Dynamo-Depth does assume access to GT intrinsics during training, as loaded [here](https://github.com/YihongSun/Dynamo-Depth/blob/39affac2e95e1d97cc2d281b28b0e0a0e8d544f6/Trainer.py#L234) in the trainer.

For inference, the GT intrinsics are only used when visualizing the 3D flow field as optical flow and not used when  evaluating model predictions, including depth, odometry, and motion segmentation.

The wording in the paper (indented below) was mainly written in the context of training a monocular depth estimator without any GT LiDAR values, GT semantic mask/bbox annotations, or off-the-shelf detector predictions. Sorry for any confusion about this. 
> On all datasets, we only use the unlabeled video frames for training; ground truth LiDAR depth is only used for evaluation.

Feel free to reply if you have any other questions or concerns!

**Comment by andrewsonga** [comment]
Thank you for the detailed response Yihong! Looking forward to your follow-up projects!

**Comment by andrewsonga** [comment]
Thank you for the detailed response Yihong! Looking forward to your follow-up projects!
