### ISSUE TITLE
Something about the Dataset Preprocess

### ISSUE THREAD

**Issue by Kevinskr** [YihongSun/Dynamo-Depth#4]
Thank you for your amazing repository!
But when I ran the code "prepare_data/nuScenes.py", an error occurred with the information "KeyError: 'index' " in line  71. Then I checked the file "category.json" in "v1.0-trainval" and did not find the key "index". Should I add the key "index" by myself or is there something wrong with my dataset?
Look forward to your reply.

**Comment by YihongSun** [comment]
Hello,

Thank you for your interest in our work!

There is indeed a slight error in data processing [README](https://github.com/YihongSun/Dynamo-Depth/blob/main/prepare_data/README.md) that has been fixed.

`v1.0-trainval/category.json` from the `Full dataset (v1.0)` does not contain "index" as you pointed out, but once `nuScenes-panoptic-v1.0-all.tar` is unzipped into the same directory, `v1.0-trainval/category.json` is overwritten. I have attached a snippet below to show the differences on `v1.0-mini`. For the purpose of our codebase, this file replacement is ok.

`v1.0-mini/category.json`:
```
[
{
"token": "1fa93b757fc74fb197cdd60001ad8abf",
"name": "human.pedestrian.adult",
"description": "Adult subcategory."
},
{
"token": "b1c6de4c57f14a5383d9f963fbdcb5cb",
"name": "human.pedestrian.child",
"description": "Child subcategory."
},
...
```

`nuScenes-panoptic-v1.0-all/v1.0-mini/category.json`:
```
[
  {
    "token": "aaddc3454ccbefbb2d8d8461f8f7f481",
    "name": "noise",
    "description": "Any lidar return that does not correspond to a physical object, such as dust, vapor, noise, fog, raindrops, smoke and reflections.",
    "index": 0
  },
  {
    "token": "63a94dfa99bb47529567cd90d3b58384",
    "name": "animal",
    "description": "All animals, e.g. cats, rats, dogs, deer, birds.",
    "index": 1
  },
...
```

**Comment by YihongSun** [comment]
Closed due to inactivity.
